"""
Author: Jessica M. Gonzalez-Delgado
        North Carolina State University

This script converts an NMR peak list file generated by TopSpin [XML]
to a peak list file to be read by Poky/Sparky [LIST].

Run as: python xml2list.py file.xml
"""

import sys
import argparse
import xml.etree.ElementTree as ET


def parse_xml(xml_file):
    """Read data from XML file."""
    tree = ET.parse(xml_file)
    root = tree.getroot()
    peaks = []

    for peak in root.findall('.//Peak2D'):
        residue = peak.get('annotation')
        w1 = peak.get('F1')
        w2 = peak.get('F2')
        data_height = peak.get('intensity')
        peaks.append((residue, w1, w2, data_height))

    return peaks


def write_list(peaks, list_file):
    """Write LIST file."""
    with open(list_file, 'w') as fo:
        fo.write("Assignment    w1    w2    Data Height\n")
        for peak in peaks:
            fo.write("    ".join(peak) + "\n")


def main():
    """Main program"""
    parser = argparse.ArgumentParser(description='Convert an NMR peak list file from XML to LIST format.')
    parser.add_argument('xml_file', type=str, help='Input XML file')
    args = parser.parse_args()

    if args.xml_file[-3:] != 'xml':
        print("Incorrect file format.\nExiting now...")
        sys.exit()
    else:
        peaks = parse_xml(args.xml_file)
        write_list(peaks, args.xml_file[:-3]+'list')

    print("Done.")


"""Run program"""
if __name__ == '__main__':
    main()
